version: "2"
services:
  node:
    container_name: node
    image: node:10.14.1
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
    entrypoint: /home/node/app/entrypoint.sh